apiVersion: v1
kind: Pod
metadata:
  name: myconfigmappod
  namespace: purple
spec:
  containers:
    - name: myconfigmappod-container
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
      env:
        - name: MY_EXAM_ENV
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: exame
  restartPolicy: Never
