apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  namespace: blue
spec:
  storageClassName: "manual"
  accessModes:
    - "ReadWriteOnce"
  capacity:
    storage: 1Gi
  hostPath:
    path: /data