apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s
  namespace: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs-k8s
  template:
    metadata:
      labels:
        app: nodejs-k8s
    spec:
      containers:
        - name: nodejs-k8s
          image: mohamadalsalty/nodejs-k8s:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 100
            runAsGroup: 101
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: dev
spec:
  selector:
    app: nodejs-k8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: dev
spec:
  rules:
    - host: www.nodejs.local.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodejs-cronjob
  namespace: dev
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello Nodejs app
          restartPolicy: OnFailure
