apiVersion: v1
kind: Namespace
metadata:
  name: dev
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-k8s
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-k8s
  template:
    metadata:
      labels:
        app: nodejs-k8s
    spec:
      containers:
        - name: nodejs-k8s
          image: mohamadalsalty/nodejs-k8s:latest
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: dev
spec:
  selector:
    app: nodejs-k8s
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: dev
spec:
  rules:
    - host: www.nodejs.local.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nodejs-service
                port:
                  number: 3000
