apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-backend
  template:
    metadata:
      labels:
        app: apache-backend
    spec:
      containers:
        - name: apache-backend
          image: httpd:latest
          ports:
            - containerPort: 80

