apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  selector:
    app: apache-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

